// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ianpvnfqpixpvkmagkvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhbnB2bmZxcGl4cHZrbWFna3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzcxMTMsImV4cCI6MjA1OTE1MzExM30.xwemRlf4Wm1264KWkHyEnEkQ3AXbHljbUnYXiJkEIgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);